baseURL = 'https://hackathonrimac.com'
title = 'Hackathon Rimac'
theme = 'hugo-bootstrap'

disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  reto = "retos"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"

  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.parser]
      autoHeadingID = true
      wrapStandAloneImageWithinParagraph = false

      [markup.goldmark.parser.attribute]
        block = true
        title = true

    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = false


# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
[params]
  description = "Participa en el Hackathon RIMAC 2025 del 21 al 23 de noviembre construyendo soluciones disruptivas en healthcare y data."
  images = ['images/hackathonrimac-card-2025.jpg']
  mainMenuLogo = "images/hackathonlogo.png"
  copyright="2025 RIMAC Seguros y Reaseguros"

  themeColor = "#fff"

  [params.options]
    bootStrapJs = true
    breadCrumb = false
    listCategoryFilter = true
    listTagFilter = true
    typeform_id_short = "ChWpd8oq"
    typeform_id_long = "01K8BNY6R5FWFTY9J54752SP0C"
  
[[menus.main]]
name = "Inicio"
url = "/"
weight = 10

[[menus.main]]
name = "Retos"
url = "/#retos"
weight = 20

[[menus.main]]
name = "Información"
url = "/faq"
weight = 30

